### PR TITLE
users now have a chance to name themselves when they skipped the oppo…

### PR DESCRIPTION
**Pull request by rjmk**
…rtunity

Also fixes a couple of typos in the README and moves comments that I forgot to move with the last PR.

### CODE REVIEW

**Comment by nelsonic** [comment]
@rjmk which line(s) give the person the opportunity to name themselves?

**Comment by rjmk** [comment]
Sorry @nelsonic, should have said -- code was already in place on line 53 in client.js but wasn't triggering correctly in the case of the name 'null', so line 7 lets it trigger

**Comment by nelsonic** [comment]
Looks good. thanks! :+1:

**Comment by iteles** [comment]
@rjmk We'll have to remember to add this is a PR from you to the riot version of the tutorial right at the end!

**Pull request merged**
