### PR TITLE
Dependency update

### PR DESCRIPTION
**Pull request by nelsonic**
Fixes https://github.com/dwyl/hapi-socketio-redis-chat-example/issues/42

### CODE REVIEW

**Comment by nelsonic** [comment]
@iteles sorry, wasn't expecting travis build to fail... :disappointed:

**Comment by nelsonic** [comment]
The Build Passes on my Local...
hapi-socketio-redis-chat-example-tests-passing

**Comment by nelsonic** [comment]
I've posted a question (*request for support*) on `hiredis-node`: https://github.com/redis/hiredis-node/issues/107

**Comment by nelsonic** [comment]
@iteles please review+merge. thanks. :+1:

**Comment by iteles** [comment]
:+1:

**Pull request merged**
