### PR TITLE
Stop blank messages sending

### LINKED ISSUE #35: Blank chat messages should not send
screen shot 2015-08-12 at 11 28 19

### PR DESCRIPTION
**Pull request by tsop14**
Stops :hand: pesky/boring :boar: blank messages from being sent and adds a helpful placeholder to suggest people "please enter your message here". 

Fixes #35

### CODE REVIEW

**Comment by iteles** [comment]
I like that it only shows up if you _try_ to send a blank message!

If you add a space or two you can still send a blank message though :blush: Do you have time to look into the required [regular expression](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/RegExp)?

**Comment by nelsonic** [comment]
Sweet! :lollipop:

**Comment by tsop14** [comment]
@iteles good idea! Done.

**Comment by iteles** [comment]
Just tried this out on Chrome and trying to submit a blank message triggers the placeholder, but trying to submit a space doesn't.

Did it work for you in Firefox?

**Comment by tsop14** [comment]
@iteles Atm, if you've entered whitespace the placeholder will not appear. 

The reason being the placeholder cannot show if you have _something_ in the box, in this case it has whitespace. To solve this you would need to empty the box (and move the pointer back to the start?)  - can try this.

**Comment by iteles** [comment]
@tsop14 That makes perfect sense of course. 

If we're blocking the action though, we do need to provide some feedback on what's happening. I like your solution!

**Comment by tsop14** [comment]
:cry: why is this still open?

**Comment by iteles** [comment]
:heart: Works like a _charm_, thanks @tsop14! :star:

Sorry it took me so long to merge, I must have missed the notification that there was a change :cry:

**Pull request merged**
