### PR TITLE
Adds styles to allow scrolling to content behind form 

### LINKED ISSUE #8: CSS Bug - Message input covers messages list
when there are _enough_ messages to fill the screen, the input covers the last message(s):
css-message-input-covers-messages-list

### PR DESCRIPTION
**Pull request by iteles**
Trying to resolve #8 but not quite there yet.
There are three parts to this issue:
1. The form input box is cut off at the bottom
2. The content behind the form input box cannot be accessed, even with scrolling
3. Doesn't overlap content when new content is added

### CODE REVIEW

**Comment by iteles** [comment]
So far, with a CSS-only solution, 1 and 2 are resolved.
Still working on 3.

**Comment by nelsonic** [comment]
I'm _excited_ that you're even _attempting_ to solve this with CSS-only ...! :wink:

**Comment by iteles** [comment]
To solve #8, it turns out I need to solve #21 and #22 as well.
After spending a _day_ trying to do this with CSS, I conceded that there wasn't a CSS-only solution (got a [great answer to my stackoverflow question](http://stackoverflow.com/a/31497034/2870306) but didn't resolve the issue as it prevented people from scrolling back up to see older messages).
#21 and #22 will be solved with Javascript.

**Comment by iteles** [comment]
@nelsonic Ready to merge when tests pass! Solves #8, #21 and #22.

**Comment by nelsonic** [comment]
Sweet! :candy: 
Thanks! :+1:

**Pull request merged**
