### PR TITLE
Use newer gcc to make sure hiredis-node compiles

### PR DESCRIPTION
**Pull request by badboy**
See https://github.com/redis/hiredis-node/issues/107

### CODE REVIEW

**Comment by nelsonic** [comment]
Thanks @badboy :+1: 
We saw this issue when trying to update to the latest version of Node.js ...
Please Try updating to Node `v.4.2.2` in the `.travis.yml` and see if the build still passes ...

**Comment by nelsonic** [comment]
This does not work for Node V4 but its a good starting point.

**Comment by badboy** [comment]
It's not?

**Comment by nelsonic** [comment]
As soon as we tried using Node V4.2.2 `hiredis` would not compile on Travis-CI

**Pull request merged**
