### PR TITLE
with @jackcarlisle fixes hanging 7th test 

### PR DESCRIPTION
**Pull request by hdrdavies**

### CODE REVIEW

**Comment by nelsonic** [comment]
@hdrdavies is there an issue/bug filed for this?

**Comment by hdrdavies** [comment]
@nelsonic when you clone the repo and ```npm run test``` the 7th test hangs.

Would you have preferred us to raise an issue before making a PR?

**Comment by nelsonic** [comment]
@hdrdavies yes, please, (*always*) raise the issue with as much info as possible *before* creating a PR to fix it. :+1: 
@iteles where should this be made *clearererer* in the process?

**Comment by iteles** [comment]
@nelsonic In the repo that results from [this issue](https://github.com/dwyl/hq/issues/48) when we get a second!

**Comment by hdrdavies** [comment]
@nelsonic :+1: awesome. Will do now & from now on.

**Comment by nelsonic** [comment]
@hdrdavies if you don't mind describing the problem as an issue it will set a good example for others to follow. from the reviewer's perspective it *looks* like the build works: https://travis-ci.org/dwyl/hapi-socketio-redis-chat-example/builds

**Comment by hdrdavies** [comment]
@nelsonic in the process of raising an issue :+1: :beetle:

**Comment by nelsonic** [comment]
This PR fixes issue: https://github.com/dwyl/hapi-socketio-redis-chat-example/issues/49 (testing hanging)

**Pull request merged**
